// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ9EylTYH3PciFzJAhQWMQUVA5dR2l-9A',
    appId: '1:1567941263:web:f96affff1a458b1c2686fa',
    messagingSenderId: '1567941263',
    projectId: 'flutter-manga-7a1c9',
    authDomain: 'flutter-manga-7a1c9.firebaseapp.com',
    databaseURL: 'https://flutter-manga-7a1c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-manga-7a1c9.appspot.com',
    measurementId: 'G-4GEFMK34P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTq1baxGFPeeyr1d5j3StCLTvjj1Zjnfo',
    appId: '1:1567941263:android:e9569b4a9bde3c7c2686fa',
    messagingSenderId: '1567941263',
    projectId: 'flutter-manga-7a1c9',
    databaseURL: 'https://flutter-manga-7a1c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-manga-7a1c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjaZYBcMPyZdH_9drW7c0GTJpJJit8U5Y',
    appId: '1:1567941263:ios:9b99eb87c4ccc4bd2686fa',
    messagingSenderId: '1567941263',
    projectId: 'flutter-manga-7a1c9',
    databaseURL: 'https://flutter-manga-7a1c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-manga-7a1c9.appspot.com',
    iosClientId: '1567941263-1gol5th5k34s4dobp2um8ea60ou33571.apps.googleusercontent.com',
    iosBundleId: 'com.example.clonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjaZYBcMPyZdH_9drW7c0GTJpJJit8U5Y',
    appId: '1:1567941263:ios:9b99eb87c4ccc4bd2686fa',
    messagingSenderId: '1567941263',
    projectId: 'flutter-manga-7a1c9',
    databaseURL: 'https://flutter-manga-7a1c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-manga-7a1c9.appspot.com',
    iosClientId: '1567941263-1gol5th5k34s4dobp2um8ea60ou33571.apps.googleusercontent.com',
    iosBundleId: 'com.example.clonApp',
  );
}
